apiVersion: v1
kind: Service
metadata:
  name: friendly-hello-svc
  labels:
    app: friendly-hello
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30081
  selector:
    app: friendly-hello