apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendly-hello-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friendly-hello-k8s
  template:
    metadata:
      labels:
        app: friendly-hello-k8s
    spec:
      containers:
      - name: friendly-hello-k8s
        imagePullPolicy: IfNotPresent
        image: registry.cn-hangzhou.aliyuncs.com/liangzhinian/friendly-hello-k8s:latest #katacoda/docker-http-server:latest
        ports:
        - containerPort: 8080